djangoapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('users.urls')),
    path('pizza/', include('pizza.urls')),
    path('studenci/', include('studenci.urls')),
    path('users/', include('users.urls')),
    path('admin/', admin.site.urls),
]

pizza/urls.py
from django.urls import path

from . import views

app_name='pizza'
urlpatterns = [
    path('', views.index, name='index'),
    path('news', views.news, name='news'),
]

studenci/urls.py
from django.urls import path

from . import views
from django.views.generic import ListView
from studenci.models import Miasto

app_name = 'studenci'
urlpatterns = [
	path('', views.index, name='index'),
    path('miasta/lista', ListView.as_view(model=Miasto), name='miasta_lista'),
    path('miasta/', views.miasta, name='miasta'),
    path('miasta/dodaj', views.DodajMiasto.as_view(), name='miasta_dodaj'),
    path('miasta/edytuj/<int:pk>', views.EdytujMiasto.as_view(), name='miasta_edytuj'),
    path('miasta/usun/<int:pk>', views.UsunMiasto.as_view(), name='miasta_usun'),
    path('uczelnie/', views.uczelnie, name='uczelnie'),
    path('uczelnie/lista', views.ListaUczelni.as_view(), name='uczelnie_lista'),
    path('login/', views.login, name='login'),
]

pizza/models.py
from django.db import models

class Pizza(models.Model):
    LARGE = 'L'
    MEDIUM = 'M'
    SMALL = 'S'
    ROZMIARY = (
        (LARGE, 'duża'),
        (MEDIUM, 'średnia'),
        (SMALL, 'mała'),
    )
    nazwa = models.CharField(verbose_name='pizza', max_length=30, help_text='Nazwa pizzy')
    opis = models.TextField(blank=True, default='', help_text='Opis pizzy')
    rozmiar = models.CharField(max_length=1, choices=ROZMIARY, default=LARGE)
    cena = models.DecimalField(max_digits=5, decimal_places=2, default=0)
    data = models.DateField('dodano', auto_now_add=True)

    def __str__(self):
        return self.nazwa;

    class Meta:
        verbose_name_plural = "pizze"

class Skladnik(models.Model):
    pizze = models.ManyToManyField(Pizza, related_name='skladniki', blank=True)
    nazwa = models.CharField('składnik', max_length=30)
    jarski = models.BooleanField(
        'jarski?',
        help_text='Zaznacz, jeżeli składnik jest odpowiedni dla wegetarian',
        default=False)
    cena = models.DecimalField(max_digits=3, decimal_places=2, default=0)

    def __str__(self):
        return self.nazwa

    class Meta:
        verbose_name_plural = "skladniki"

studenci/models.py
from django.db import models


class Uczelnia(models.Model):
    nazwa = models.CharField(verbose_name='uczelnia', max_length=30)

    def __str__(self):
        return self.nazwa

    class Meta:
        verbose_name_plural = "uczelnie"

class Miasto(models.Model):
    nazwa = models.CharField(verbose_name='miasto', max_length=30)
    kod = models.CharField(max_length=6, help_text="Wpisz kod pocztowy")

    def __str__(self):
        return self.nazwa

    class Meta:
        verbose_name_plural = "miasta"

class Student(models.Model):
    imie = models.CharField(max_length=30)
    nazwisko = models.CharField(max_length=30)
    uczelnia = models.ForeignKey(Uczelnia, on_delete=models.SET_NULL, null=True)
    miasto = models.ForeignKey(Miasto, on_delete=models.SET_NULL, null=True)
    roks = models.CharField('rok studiów', max_length=3, blank=True, default='')
    dochod = models.DecimalField(max_digits=6, decimal_places=2, default=0)

    def __str__(self):
        return self.imie + ' ' + self.nazwisko

    class Meta:
        verbose_name_plural = "studenci"

pizza/views.py
from django.shortcuts import render
from django.http import HttpResponse

def index(request):
    #return HttpResponse("Witaj  w barze Pizza!")
    return render(request, 'pizza/index.html')

def news(request):
    #return HttpResponse("Nowości")
    return render(request, 'pizza/news.html')

studenci/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib import messages
from django.urls import reverse

from studenci.models import Miasto, Uczelnia
from studenci.forms import StudentLoginForm, UczelniaForm, MiastoForm, MiastoModelForm

from django.views.generic import ListView, DeleteView
from django.views.generic.edit import CreateView, UpdateView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin

def index(request):
    # return HttpResponse("Witaj w aplikacji Studenci!")
    return render(request, 'studenci/index.html')


def miasta(request):
    if request.method == 'POST':
        form = MiastoForm(request.POST)
        # nazwa = request.POST.get('nazwa')
        # kod = request.POST.get('kod')
        # if len(nazwa.strip()):
        if form.is_valid():
            m = Miasto(nazwa=form.cleaned_data['nazwa'], kod=form.cleaned_data['kod'])
            m.save()
            messages.success(request, "Dane zapisano!")
            return redirect(reverse('studenci:miasta'))
        else:
            messages.error(request, "Błędne dane!")
    else:
        form = MiastoForm()

    miasta = Miasto.objects.all()
    kontekst = {
        'miasta': miasta,
        'form': form
    }

    return render(request, 'studenci/miasta.html', kontekst)


def uczelnie(request):

    if request.method == 'POST':
        form = UczelniaForm(request.POST)
        if form.is_valid():
            # print(form.cleaned_data)
            u = Uczelnia(nazwa=form.cleaned_data['nazwa'])
            u.save()
            messages.success(request, "Dane zapisano!")
            # przekierowanie
            return redirect(reverse('studenci:uczelnie'))
    else:
        form = UczelniaForm()

    uczelnie = Uczelnia.objects.all()
    kontekst = {
        'form': form,
        'uczelnie': uczelnie
    }

    if request.user.has_perm('studenci.add_uczelnia'):
        return render(request, 'studenci/uczelnie.html', kontekst)
    else:
        messages.info(request, "Nie możesz dodawać uczelni.")
        return redirect(reverse('studenci:index'))


def login(request):
    if request.method == 'POST':
        pass
    else:
        form = StudentLoginForm()

    kontekst = { 'form': form }
    return render(request, 'studenci/login.html', kontekst)


class ListaUczelni(ListView):
    model = Uczelnia
    context_object_name = 'uczelnie'
    template_name = 'studenci/lista_uczelni.html'


@method_decorator(login_required, name='dispatch')
class DodajMiasto(CreateView):
    model = Miasto
    fields = ('nazwa', 'kod')
    template_name = 'studenci/miasto_dodaj.html'
    success_url = reverse_lazy('studenci:miasta_lista')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['miasta'] = Miasto.objects.all()
        return context

    def form_valid(self, form):
        messages.success(self.request, "Dodano miasto!")
        return super().form_valid(form)


@method_decorator(login_required, name='dispatch')
class EdytujMiasto(SuccessMessageMixin, UpdateView):
    model = Miasto
    form_class = MiastoModelForm
    template_name = 'studenci/miasto_dodaj.html'
    success_url = reverse_lazy('studenci:miasta_lista')
    success_message = 'Zaktualizowano miasto!'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['miasta'] = Miasto.objects.all()
        return context

class UsunMiasto(DeleteView):
    model = Miasto
    success_url = reverse_lazy('studenci:miasta_lista')

pizza/templates/pizza/index.html
{% extends 'szablon.html' %}
{% block tytul %}Pizza{% endblock tytul %}

{% block naglowek %} Witaj w barze Pizza!{% endblock naglowek %}
{% block tresc %}
<p>Oferujemy szeroki wybór pizzy i nie tylko</p>
{% endblock tresc %}

studenci/templates/studenci/miasta.html
{% extends 'szablon.html' %}
{% block naglowek %}Miasta{% endblock naglowek %}
{% block tresc %}

<h2>Dodaj miasto</h2>
    {% if user.is_authenticated %}
        {% if perms.studenci.add_miasto %}
            <form action="." method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="Zapisz">
            </form>
        {% else %}
            <div class="well">Nie możesz dodawać miast!</div>
        {% endif %}
    {% endif %}

<h2>Lista miast</h2>
<ol>
    {% for miasto in miasta %}
        <li>{{ miasto.nazwa }}&nbsp;{{ miasto.kod }}</li>
    {% endfor %}
</ol>

{% endblock tresc %}

studenci/templates/studenci/uczelnie.html
{% extends 'szablon.html' %}
{% block naglowek %}Uczelnie{% endblock naglowek %}
{% block tresc %}

<h2>Dodaj uczelnię</h2>
    <form method="POST">
    {% csrf_token %}
        {{ form.as_p }}
<!--        <input type="text" name="nazwa" size="30" maxlength="30"> -->
        <input type="submit" value="Zapisz">
    </form>

<h2>Lista uczelni</h2>
<ol>
    {% for uczelnia in uczelnie %}
        <li>{{ uczelnia.nazwa }} – <a href="{% url 'studenci:uczelnie_edytuj' uczelnia.id %}">Edytuj</a></li>
    {% endfor %}
</ol>

{% endblock tresc %}

studenci/templates/szablon.html
<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block tytul %}Projekt Django{% endblock tytul %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>

    <nav class="navbar navbar-expand-sm bg-light">
        <a class="navbar-brand" href="http://lo1.sandomierz.pl">I LO CG</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
            <ul class="navbar-nav">
            <li class="nav-item dropdown">
                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button">Pizza</a>
                <div class="dropdown-menu">
                    <a href="{% url 'pizza:index' %}" class="dropdown-item">Strona główna</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button">Studenci</a>
                <div class="dropdown-menu">
                    <a href="{% url 'studenci:index' %}" class="dropdown-item">Strona główna</a>
                    <a href="{% url 'studenci:miasta_lista' %}" class="dropdown-item">Lista miast</a>
                    <a href="{% url 'studenci:miasta_dodaj' %}" class="dropdown-item">Utwórz miasto</a>
                    <a href="{% url 'studenci:miasta' %}" class="dropdown-item">Dodaj miasto</a>
                    <a href="{% url 'studenci:uczelnie_lista' %}" class="dropdown-item">Lista uczelni</a>
                    <a href="{% url 'studenci:uczelnie' %}" class="dropdown-item">Doaj uczelnię</a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button">Użytkownicy</a>
                <div class="dropdown-menu">
                    <a href="{% url 'users:index' %}" class="dropdown-item">Strona główna</a>
                    {% if not user.is_authenticated %}
                        <a href="{% url 'users:rejestruj' %}" class="dropdown-item">Rejestracja</a>
                        <a href="{% url 'users:loguj' %}" class="dropdown-item">Logowanie</a>
                    {% else %}
                        <a href="{% url 'users:wyloguj' %}" class="dropdown-item">Wyloguj</a>
                    {% endif %}

                </div>
            </li>
            </ul>
        </div>
    </nav>

    <div class="container">
        <div class="row">
            <div class="col">

    <h1>{% block naglowek %}Aplikacja Django{% endblock naglowek %}</h1>

    {% if messages %}
    <ul>
        {% for komunikat in messages %}
        <li>{{ komunikat }}</li>
        {% endfor %}
    </ul>
    {% else %}
        <p>Brak komunikatów.</p>
    {% endif %}

    {% block tresc %}{% endblock tresc %}

            </div>
        </div>
    </div>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</body>
</html>